name: Pull request to develop
on: pull_request

jobs:
  build:
    name: ESLint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - uses: gimenete/eslint-action@1.0
      - uses: tinovyatkin/action-eslint@v1
        env:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          check-name: eslint
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}