name: Pull request to develop
on: pull_request

jobs:
  build:
    name: ESLint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: gimenete/eslint-action@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
