name: Pull request to develop
on: pull_request

jobs:
  build:
    name: ESLint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      # - uses: gimenete/eslint-action@1.0
      - uses: rkusa/eslint-action@1.0.0
        # with:
        #     args: "eslint '**/*.js'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}